[2023-02-20T15:21:06.917+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ifgoiano_site_dag.get_data manual__2023-02-20T15:21:04.866528+00:00 [queued]>
[2023-02-20T15:21:06.945+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ifgoiano_site_dag.get_data manual__2023-02-20T15:21:04.866528+00:00 [queued]>
[2023-02-20T15:21:06.946+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T15:21:06.946+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-20T15:21:06.946+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T15:21:06.984+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_data> on 2023-02-20 15:21:04.866528+00:00
[2023-02-20T15:21:06.998+0000] {standard_task_runner.py:55} INFO - Started process 906 to run task
[2023-02-20T15:21:07.012+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ifgoiano_site_dag', 'get_data', 'manual__2023-02-20T15:21:04.866528+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ifgoiano_site_dag.py', '--cfg-path', '/tmp/tmpbul3t32o']
[2023-02-20T15:21:07.016+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask get_data
[2023-02-20T15:21:07.143+0000] {task_command.py:388} INFO - Running <TaskInstance: ifgoiano_site_dag.get_data manual__2023-02-20T15:21:04.866528+00:00 [running]> on host f5b6b7502b7e
[2023-02-20T15:21:07.296+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Rafael
AIRFLOW_CTX_DAG_ID=ifgoiano_site_dag
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T15:21:04.866528+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T15:21:04.866528+00:00
[2023-02-20T15:21:07.300+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2023-02-20T15:21:11.620+0000] {logger.py:11} INFO - Get LATEST chromedriver version for chromium 110.0.5481
[2023-02-20T15:21:14.801+0000] {logger.py:11} INFO - There is no [linux64] chromedriver for browser 110.0.5481 in cache
[2023-02-20T15:21:14.820+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux64.zip
[2023-02-20T15:21:15.103+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading:   0%|          | 0.00/7.05M [00:00<?, ?B/s]
[2023-02-20T15:21:15.215+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading:  11%|#         | 792k/7.05M [00:00<00:00, 8.08MB/s]
[2023-02-20T15:21:15.470+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading:  22%|##1       | 1.55M/7.05M [00:00<00:01, 4.12MB/s]
[2023-02-20T15:21:15.803+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading:  29%|##8       | 2.04M/7.05M [00:00<00:02, 2.61MB/s]
[2023-02-20T15:21:15.905+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading:  35%|###4      | 2.45M/7.05M [00:00<00:01, 2.95MB/s]
[2023-02-20T15:21:16.010+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading:  50%|#####     | 3.54M/7.05M [00:00<00:00, 4.77MB/s]
[2023-02-20T15:21:16.113+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading:  79%|#######8  | 5.55M/7.05M [00:01<00:00, 8.60MB/s]
[2023-02-20T15:21:16.162+0000] {logging_mixin.py:137} WARNING - [WDM] - Downloading: 100%|##########| 7.05M/7.05M [00:01<00:00, 7.00MB/s]
[2023-02-20T15:21:17.178+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/110.0.5481]
[2023-02-20T15:21:18.482+0000] {logging_mixin.py:137} INFO - ----- Bot is running -----
[2023-02-20T15:21:18.547+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ifgoiano_site_dag.py", line 678, in get_data
    with Bot() as bot:
AttributeError: __enter__
[2023-02-20T15:21:18.572+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=ifgoiano_site_dag, task_id=get_data, execution_date=20230220T152104, start_date=20230220T152106, end_date=20230220T152118
[2023-02-20T15:21:18.599+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task get_data (__enter__; 906)
[2023-02-20T15:21:18.658+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-20T15:21:18.700+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
